/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    InlineForm: typeof import('./src/components/InlineForm.vue')['default']
    PatientDetail: typeof import('./src/components/PatientDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
