# Generated by Django 5.2.4 on 2025-07-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='组名称')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_ID', models.CharField(max_length=10, unique=True, verbose_name='登记号')),
                ('document_ID', models.CharField(max_length=10, null=True, verbose_name='住院号')),
                ('full_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄（月）')),
                ('in_date', models.DateField(verbose_name='入院日期')),
                ('weight', models.FloatField(verbose_name='体重（Kg）')),
                ('height', models.FloatField(verbose_name='身高（cm）')),
                ('resistance', models.BooleanField(default=False, verbose_name='IVIG 抵抗')),
                ('relapse', models.BooleanField(default=False, verbose_name='复发')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawasaki.enrollgroup', verbose_name='分组')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人',
            },
        ),
        migrations.CreateModel(
            name='OtherTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='检验日期')),
                ('pct', models.FloatField(blank=True, null=True, verbose_name='降钙素原')),
                ('crp', models.FloatField(blank=True, null=True, verbose_name='超敏C反应蛋白')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawasaki.patient', verbose_name='病人')),
            ],
            options={
                'verbose_name': '其他辅助检查',
                'verbose_name_plural': '其他辅助检查',
            },
        ),
        migrations.CreateModel(
            name='LiverFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='检验日期')),
                ('ast', models.IntegerField(blank=True, null=True, verbose_name='AST')),
                ('alt', models.IntegerField(blank=True, null=True, verbose_name='ALT')),
                ('pa', models.IntegerField(blank=True, null=True, verbose_name='前白蛋白')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawasaki.patient', verbose_name='病人')),
            ],
            options={
                'verbose_name': '肝功能',
                'verbose_name_plural': '肝功能',
            },
        ),
        migrations.CreateModel(
            name='Echocardiography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='检验日期')),
                ('lmca', models.FloatField(verbose_name='左主干')),
                ('lmca_z', models.FloatField(blank=True, null=True, verbose_name='左主干Z值')),
                ('rca', models.FloatField(verbose_name='右支')),
                ('rca_z', models.FloatField(blank=True, null=True, verbose_name='右支Z值')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawasaki.patient', verbose_name='病人')),
            ],
            options={
                'verbose_name': '心脏彩超',
                'verbose_name_plural': '心脏彩超',
            },
        ),
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='检验日期')),
                ('wbc', models.FloatField(verbose_name='白细胞计数')),
                ('ne', models.FloatField(verbose_name='中性粒占比（%）')),
                ('ly', models.FloatField(verbose_name='淋巴占比（%）')),
                ('mo', models.FloatField(verbose_name='单核占比（%）')),
                ('rbc', models.FloatField(verbose_name='红细胞计数')),
                ('plt', models.FloatField(verbose_name='血小板计数')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawasaki.patient', verbose_name='病人')),
            ],
            options={
                'verbose_name': '血常规',
                'verbose_name_plural': '血常规',
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, unique=True, verbose_name='标签')),
                ('date', models.DateField(verbose_name='收集日期')),
                ('sample_type', models.CharField(choices=[('0', '全血'), ('1', '血清'), ('2', '血浆'), ('3', 'PBMCs'), ('4', '其他组织')], max_length=1, verbose_name='标本类型')),
                ('sample_status', models.CharField(choices=[('0', '待处理'), ('1', '已处理'), ('2', '已销毁')], max_length=1, verbose_name='标本状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawasaki.patient', verbose_name='病人')),
            ],
            options={
                'verbose_name': '标本',
                'verbose_name_plural': '标本',
            },
        ),
    ]
