# Generated by Django 5.2.4 on 2025-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasaki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='echocardiography',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='liverfunction',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='othertest',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='samples',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
