# Generated by Django 5.2.4 on 2025-07-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasaki', '0002_bloodtest_version_echocardiography_version_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherTest',
            new_name='InfectiousTest',
        ),
        migrations.AlterModelOptions(
            name='infectioustest',
            options={'verbose_name': '感染性指标', 'verbose_name_plural': '感染性指标'},
        ),
        migrations.AddField(
            model_name='liverfunction',
            name='alb',
            field=models.FloatField(blank=True, null=True, verbose_name='白蛋白'),
        ),
        migrations.AddField(
            model_name='liverfunction',
            name='db',
            field=models.FloatField(blank=True, null=True, verbose_name='直接胆红素'),
        ),
        migrations.AddField(
            model_name='liverfunction',
            name='tb',
            field=models.FloatField(blank=True, null=True, verbose_name='总胆红素'),
        ),
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('test_name', models.CharField(max_length=100, verbose_name='检验名称')),
                ('test_date', models.DateField(verbose_name='检验日期')),
                ('result', models.FloatField(verbose_name='检验结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawasaki.patient', verbose_name='病人')),
            ],
            options={
                'verbose_name': '其他辅助检查',
                'verbose_name_plural': '其他辅助检查',
                'abstract': False,
            },
        ),
    ]
