# Generated by Django 5.2.4 on 2025-07-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasaki', '0004_rename_test_date_customtest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customtest',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='echocardiography',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infectioustest',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='liverfunction',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='samples',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
