# Generated by Django 5.2.4 on 2025-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasaki', '0005_alter_bloodtest_version_alter_customtest_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liverfunction',
            name='pa',
        ),
        migrations.AlterField(
            model_name='liverfunction',
            name='tb',
            field=models.FloatField(blank=True, null=True, verbose_name='总蛋白'),
        ),
    ]
