# Generated by Django 5.2.4 on 2025-07-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasaki', '0006_remove_liverfunction_pa_alter_liverfunction_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liverfunction',
            old_name='db',
            new_name='dbil',
        ),
        migrations.AddField(
            model_name='liverfunction',
            name='tbil',
            field=models.FloatField(blank=True, null=True, verbose_name='总胆红素'),
        ),
    ]
